### PR TITLE
Check nginx config file during Travis tests

### PR DESCRIPTION
**Pull request by chmreid**
This adds a step to the Travis CI tests that tests the nginx configuration files to ensure they contian valid syntax. This happens after the `install_bootstrap` step, so the real config files are already created from templates when this step runs.

<s>Note: WIP = work in progress</s>

### CODE REVIEW

**Comment by chmreid** [comment]
The step that I added to travis, to test the nginx config file syntax with `nginx -t`, is not passing because the configuration file `default.nginx_http.conf` created from the template is not a valid nginx file - there is a problem with the `map` directive at the very beginning of `default.nginx_http.conf`:

```
$ nginx -c $PWD/config/default.nginx_http.conf -t
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020/05/20 17:47:42 [emerg] 13219#13219: "map" directive is not allowed here in /home/vagrant/compose_setup/config/default.nginx_http.conf:2
nginx: configuration file /home/vagrant/compose_setup/config/default.nginx_http.conf test failed
```

AFAICT this nginx config file is put into the nginx config directory, and is then picked up and used by nginx, without any issues, in Dockstore. So, I am confused why this config file isn't validating. Am I missing a step? Is there another config file that `default.nginx_http.conf` is embedded within?

cc @denis-yuen @coverbeck

**Comment by coverbeck** [comment]
I think I see what is happening. nginx is using `etc/nginx/nginx.conf` inside the Docker image. The end of that file has:
```
include /etc/nginx/conf.d/*.conf;
```
which includes the config file you are testing via the docker-compose.yml volume

```
- ./config/default.nginx_http.conf:/etc/nginx/conf.d/default.conf:ro
```

So the map directive ends up being inside the http section of the including file, which is why it works.

I added that map directive, but I don't know nginx that well. There might be a better way to do it.

**Comment by chmreid** [comment]
Thanks for that clarification. It seems that a better strategy than installing nginx with aptitude is to use nginx via docker, and mount the configuration file into the container the same way as specified in the docker-compose file. This will also make sure that we are validating the configuration file with the correct/matching version of nginx, and not the latest version available on aptitude.

**Comment by denis-yuen** [comment]
FYI, added @chmreid to the team so you shouldn't need to create branches in your own org now

**Pull request merged**
