### PR TITLE
Update ORCID scope

### PR DESCRIPTION
**Pull request by garyluu**
For https://ucsc-cgl.atlassian.net/browse/SEAB-2734

Update the scope. This will only work on members api enabled applications...meaning i'll need to change the AWS Parameter store to match

Also see https://github.com/dockstore/dockstore-deploy/pull/219

### CODE REVIEW

**Comment by denis-yuen** [comment]
Hmmm, what happens in terms of the REST endpoint when a user attempts to request an ORCID export with the old scope (i.e. user already with a linked account)
Also curious, what screens does a user see when a user unlinks and re-links? Does ORCID remember the previous association or is it treated as a completely new request to link?

**Comment by garyluu** [comment]
> Hmmm, what happens in terms of the REST endpoint when a user attempts to request an ORCID export with the old scope (i.e. user already with a linked account)

It'll say forbidden when used with the old scope

> Also curious, what screens does a user see when a user unlinks and re-links? Does ORCID remember the previous association or is it treated as a completely new request to link?

It won't remember the previous scope

I've updated the ORCID API doc for https://ucsc-cgl.atlassian.net/browse/SEAB-2543   .  There's actually quite a few things that need to be changed and split out into separate issues

**Review by denis-yuen — APPROVED** [review]
Please create new tickets from those guidelines, I think some of the UI changes at least can be grouped

**Review by coverbeck — APPROVED** [review]

**Comment by garyluu** [comment]
Changing the entire PR because of Slack discussion.  The new scope won't work with the orcid.org which will cause problems if we use compose_setup to deploy prod without enabling members api.

**Review by coverbeck — COMMENTED** [review]
I think you need to update install_bootstrap as well. At least that's been my assumption, and I've always changed it.

**Review by denis-yuen — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]

**Pull request merged**
